name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install Python dependencies (for running pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
        env:
          PYTHONPATH: ./aceest_fitness

      # Step 4: Run unit tests using pytest
      - name: Run Pytest
        run: pytest -v
        env:
          PYTHONPATH: ./aceest_fitness

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t aceest_fitness:latest .
          
      # Step 6: Run tests inside Docker container
      - name: Run tests inside Docker
        run: |
          docker run -e PYTHONPATH=/app aceest_fitness:latest pytest -v
