name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

    # 4. Run tests
    - name: Run Pytest
      run: pytest

    # 5. Build Docker image
    - name: Build Docker image
      run: docker build -t aceest_fitness:latest .

    # 6. Optional: Run tests inside Docker
    - name: Test inside Docker
      run: docker run -e PYTHONPATH=/app aceest_fitness:latest pytest
